export type Municipio = {
  name: string;
  site: string | null;
  instagram: string | null;
  stateOfPublicCalamity: boolean;
  emergencySituation: boolean;
};

const stateOfPublicCalamity: Array<Municipio> = [
  {
    name: 'Arambaré',
    site: 'https://www.arambare.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradearambare/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Arroio do Meio',
    site: 'https://arroiodomeio.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradearroiodomeio',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Barra do Rio Azul',
    site: 'https://www.barradorioazul.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeitura_barra_do_rio_azul',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Bento Gonçalves',
    site: 'https://bentogoncalves.atende.net/',
    instagram: 'https://www.instagram.com/prefeiturabento/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Bom Retiro do Sul',
    site: 'https://bomretirodosul.rs.gov.br/',
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Candelária',
    site: 'https://candelaria.atende.net/',
    instagram: 'https://www.instagram.com/prefeitura_candelaria/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Canoas',
    site: 'https://www.canoas.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefcanoas/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Canudos do Vale',
    site: 'https://www.canudosdovale.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradecanudosdovale/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Caxias do Sul',
    site: 'https://caxias.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefacaxiasdosul/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Colinas',
    site: 'https://www.colinasrs.com.br/',
    instagram: 'https://www.instagram.com/prefeituradecolinas_rs/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Cruzeiro do Sul',
    site: 'https://cruzeiro.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradecruzeirors',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Doutor Ricardo',
    site: 'https://doutorricardo.rs.gov.br/',
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Eldorado do Sul',
    site: null,
    instagram: 'https://www.instagram.com/prefeldoradodosul/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Encantado',
    site: null,
    instagram: 'https://www.instagram.com/prefeituraencantado',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Estrela',
    site: null,
    instagram: 'https://www.instagram.com/governodeestrelars/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Fontoura Xavier',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Guaíba',
    site: null,
    instagram: 'https://www.instagram.com/prefeituradeguaiba/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Imigrante',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Lajeado',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Marques de Souza',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Montenegro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Muçum',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Pelotas',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Porto Alegre',
    site: 'https://prefeitura.poa.br/',
    instagram: 'https://www.instagram.com/prefpoa/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Putinga',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Relvado',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Rio Grande',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Rio Pardo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Roca Sales',
    site: null,
    instagram: 'https://www.instagram.com/prefeitura_rocasales/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Rolante',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Santa Cruz do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Santa Maria',
    site: null,
    instagram: 'https://www.instagram.com/prefeituradesantamaria',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Santa Tereza',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'São Jerônimo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'São José do Norte',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'São Leopoldo',
    site: null,
    instagram: 'https://www.instagram.com/prefasaoleo/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'São Lourenço do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'São Sebastião do Caí',
    site: null,
    instagram: 'https://www.instagram.com/prefeiturasscai/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'São Valentim do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'São Vendelino',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Severiano de Almeida',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Sinimbu',
    site: null,
    instagram: 'https://www.instagram.com/prefasinimbu/',
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Taquari',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Travesseiro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Venâncio Aires',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
  {
    name: 'Veranópolis',
    site: null,
    instagram: null,
    stateOfPublicCalamity: true,
    emergencySituation: false,
  },
];

const emergencySituation: Array<Municipio> = [
  {
    name: 'Aceguá',
    site: 'http://acegua.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefaacegua',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Agudo',
    site: 'https://www.agudo.rs.gov.br/',
    instagram: 'https://www.facebook.com/prefagudo/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ajuricaba',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Alecrim',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Alegrete',
    site: 'https://www.alegrete.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeitura_de_alegrete/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Alegria',
    site: 'https://www.pmalegria.rs.gov.br',
    instagram: 'https://www.instagram.com/pmalegriars/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Alpestre',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Alto Alegre',
    site: 'https://altoalegre.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefealtoalegre/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Alto Feliz',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Alvorada',
    site: 'https://www.alvorada.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradealvorada/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Amaral Ferrador',
    site: 'https://www.amaralferrador.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituraamaral/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ametista do Sul',
    site: 'https://www.ametistadosul.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradeametistadosul/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Anta Gorda',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Araricá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Aratiba',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Arroio do Tigre',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Arroio dos Ratos',
    site: null,
    instagram: 'https://www.instagram.com/prefeituraratos/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Arroio Grande',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Arvorezinha',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Augusto Pestana',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Áurea',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Balneário Pinhal',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Barão de Cotegipe',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Barra do Guarita',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Barra do Ribeiro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Barra Funda',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Barros Cassal',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Benjamin Constant do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Boa Vista Das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Boa Vista do Incra',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Boa Vista do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Bom Princípio',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Bom Progresso',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Boqueirão do Leão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Braga',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Brochier',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Caçapava do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cacequi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cachoeira do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cachoeirinha',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cacique Doble',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Caiçara',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Camaquã',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Camargo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Campina das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Campinas do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Campo Bom',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Campos Borges',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cândido Godói',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Candiota',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Canela',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Canguçu',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Capão do Leão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Capela de Santana',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Capitão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Capivari do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Carlos Barbosa',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Carlos Gomes',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Casca',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Catuípe',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Centenário',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cerrito',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cerro Branco',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cerro Grande',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cerro Grande do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Chapada',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Charqueadas',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Chiapetta',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ciríaco',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Colorado',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Condor',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Constantina',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Coqueiro Baixo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Coronel Bicaco',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Coronel Pilar',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cotiporã',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Crissiumal',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cristal',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cristal do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cruz Alta',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Cruzaltense',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'David Canabarro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Derrubadas',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dezesseis de Novembro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dilermando de Aguiar',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dois Irmãos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dois Irmãos das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dois Lajeados',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dom Feliciano',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dom Pedro de Alcântara',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Dona Francisca',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Doutor Maurício Cardoso',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Encruzilhada do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Engenho Velho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Entre Rios do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Erechim',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Erval Grande',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Erval Seco',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Espumoso',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Estação',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Esteio',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Estrela Velha',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Faxinal do Soturno',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Faxinalzinho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Fazenda Vilanova',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Feliz',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Floriano Peixoto',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Formigueiro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Forquetinha',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Fortaleza dos Valos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Frederico Westphalen',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Garibaldi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Garruchos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'General Câmara',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Gentil',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Giruá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Gramado',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Gramado dos Loureiros',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Gramado Xavier',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Gravataí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Guaporé',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Harmonia',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Herval',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Herveiras',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Humaitá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ibarama',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ibiaçá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ibirapuitã',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ibirubá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Igrejinha',
    site: null,
    instagram: 'https://www.instagram.com/municipio_igrejinha/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ijuí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ilópolis',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Independência',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Inhacorá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Iraí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Itaara',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Itapuca',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Itaqui',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Itati',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Itatiba do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ivorá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ivoti',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Jaboticaba',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Jacuizinho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Jaguarão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Jaguari',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Jari',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Jóia',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Júlio de Castilhos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Lagoa Bonita do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Lagoa dos Três Cantos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Lagoão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Lajeado do Bugre',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Lavras do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Liberato Salzano',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Maçambara',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Machadinho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Manoel Viana',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Maquiné',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Maratá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Marau',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Marcelino Ramos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Mariano Moro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Mata',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Mato Leitão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Maximiliano de Almeida',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Miraguaí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Montauri',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Mormaço',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Não-me-toque',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nonoai',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Alvorada',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Bassano',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Boa Vista',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Bréscia',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Esperança do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Palma',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Petrópolis',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Ramada',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Nova Santa Rita',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Novo Barreiro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Novo Cabrais',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Novo Hamburgo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Novo Machado',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Novo Tiradentes',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Novo Xingu',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Paim Filho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Palmares do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Palmeira Das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Palmitinho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Panambi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pantano Grande',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Paraí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Paraíso do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pareci Novo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Parobé',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Passa Sete',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Passo do Sobrado',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Passo Fundo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Paulo Bento',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Paverama',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pedras Altas',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pedro Osório',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pinhal',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pinhal Grande',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pinheirinho do Vale',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pinheiro Machado',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Piratini',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Planalto',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Poço das Antas',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pontão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ponte Preta',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Porto Lucena',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Porto Mauá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Porto Xavier',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Pouso Novo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Progresso',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Protásio Alves',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Quaraí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Quevedos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Quinze de Novembro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Redentora',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Restinga Seca',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Rio dos Índios',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Riozinho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Rodeio Bonito',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Rolador',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ronda Alta',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Rondinha',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Roque Gonzales',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Rosário do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sagrada Família',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Salto do Jacuí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Salvador das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Salvador do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santa Clara do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santa Margarida do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santa Rosa',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santa Vitória do Palmar',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santana da Boa Vista',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santiago',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santo Ângelo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santo Antônio da Patrulha',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santo Antônio do Palma',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santo Augusto',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santo Cristo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Santo Expedito do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Borja',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Domingos do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Francisco de Assis',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Gabriel',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São João do Polêsine',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Jorge',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São José Das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São José do Herval',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São José do Inhacorá',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Martinho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Martinho da Serra',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Miguel das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Paulo das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Pedro das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Pedro do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Sepé',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Valentim',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Valério do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'São Vicente do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sapiranga',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sapucaia do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sarandi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Seberi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sede Nova',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Segredo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Selbach',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Senador Salgado Filho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sentinela do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Serafina Corrêa',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sério',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sertão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sete de Setembro',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Silveira Martins',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Sobradinho',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Soledade',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tabaí',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tapera',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Taquara',
    site: null,
    instagram: 'https://www.instagram.com/preftaquara/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Taquaruçu do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tenente Portela',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Teutônia',
    site: null,
    instagram: 'https://www.instagram.com/prefeiturateutonia/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tiradentes do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Toropi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Três Arroios',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Três Coroas',
    site: null,
    instagram: 'https://www.instagram.com/prefeitura_trescoroas/',
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Três Forquilhas',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Três Palmeiras',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Três Passos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Trindade do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Triunfo',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tucunduva',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tunas',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tupanciretã',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tupandi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Tuparendi',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Ubiretama',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'União da Serra',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Uruguaiana',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vale do Sol',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vale Real',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vale Verde',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vera Cruz',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vespasiano Correa',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Viadutos',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Viamão',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vicente Dutra',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Victor Graeff',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vila Maria',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vila Nova do Sul',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vista Alegre',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vista Gaúcha',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Vitória das Missões',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
  {
    name: 'Westfalia',
    site: null,
    instagram: null,
    stateOfPublicCalamity: false,
    emergencySituation: true,
  },
];

export function GET(): Response {
  return Response.json({
    meta: {
      source: 'https://www.diariooficial.rs.gov.br/materia?id=999537',
    },
    data: [...stateOfPublicCalamity, ...emergencySituation].sort((a, b) => {
      const nameA = a.name.toUpperCase();
      const nameB = b.name.toUpperCase();

      if (nameA < nameB) {
        return -1;
      }

      if (nameA > nameB) {
        return 1;
      }

      return 0;
    }),
  });
}
