export type Municipio = {
  name: string;
  site: string | null;
  instagram: string | null;
};

export type MunicipiosResponse = {
  source: string;
  data: Array<Municipio>;
};

const municipios: Array<Municipio> = [
  {
    name: 'Aceguá',
    site: 'http://acegua.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefaacegua',
  },
  {
    name: 'Agudo',
    site: 'https://www.agudo.rs.gov.br/',
    instagram: 'https://www.facebook.com/prefagudo/',
  },
  {
    name: 'Alegrete',
    site: 'https://www.alegrete.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeitura_de_alegrete/',
  },
  {
    name: 'Alegria',
    site: 'https://www.pmalegria.rs.gov.br',
    instagram: 'https://www.instagram.com/pmalegriars/',
  },
  {
    name: 'Alto Alegre',
    site: 'https://altoalegre.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefealtoalegre/',
  },
  {
    name: 'Alvorada',
    site: 'https://www.alvorada.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradealvorada/',
  },
  {
    name: 'Amaral Ferrador',
    site: 'https://www.amaralferrador.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituraamaral/',
  },
  {
    name: 'Ametista do Sul',
    site: 'https://www.ametistadosul.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefeituradeametistadosul/',
  },
  { name: 'André da Rocha', site: null, instagram: null },
  { name: 'Anta Gorda', site: null, instagram: null },
  { name: 'Araricá', site: null, instagram: null },
  { name: 'Aratiba', site: null, instagram: null },
  {
    name: 'Arroio do Meio',
    site: null,
    instagram: 'https://www.instagram.com/prefeituradearroiodomeio',
  },
  { name: 'Arroio do Tigre', site: null, instagram: null },
  {
    name: 'Arroio dos Ratos',
    site: null,
    instagram: 'https://www.instagram.com/prefeituraratos/',
  },
  { name: 'Arroio Grande', site: null, instagram: null },
  { name: 'Arvorezinha', site: null, instagram: null },
  { name: 'Augusto Pestana', site: null, instagram: null },
  { name: 'Áurea', site: null, instagram: null },
  { name: 'Balneário Pinhal', site: null, instagram: null },
  { name: 'Barão de Cotegipe', site: null, instagram: null },
  { name: 'Barra do Guarita', site: null, instagram: null },
  { name: 'Barra do Rio Azul', site: null, instagram: null },
  { name: 'Barra Funda', site: null, instagram: null },
  { name: 'Barros Cassal', site: null, instagram: null },
  { name: 'Benjamin Constant do Sul', site: null, instagram: null },
  {
    name: 'Bento Gonçalves',
    site: 'https://bentogoncalves.atende.net/',
    instagram: 'https://www.instagram.com/prefeiturabento/',
  },
  { name: 'Boa Vista Das Missões', site: null, instagram: null },
  { name: 'Boa Vista do Buricá', site: null, instagram: null },
  { name: 'Boa Vista do Sul', site: null, instagram: null },
  { name: 'Bom Jesus', site: null, instagram: null },
  { name: 'Bom Princípio', site: null, instagram: null },
  { name: 'Bom Retiro do Sul', site: null, instagram: null },
  { name: 'Boqueirão do Leão', site: null, instagram: null },
  { name: 'Brochier', site: null, instagram: null },
  { name: 'Butiá', site: null, instagram: null },
  { name: 'Caçapava do Sul', site: null, instagram: null },
  { name: 'Cacequi', site: null, instagram: null },
  { name: 'Cachoeira do Sul', site: null, instagram: null },
  { name: 'Cachoeirinha', site: null, instagram: null },
  { name: 'Cacique Doble', site: null, instagram: null },
  { name: 'Caiçara', site: null, instagram: null },
  { name: 'Camaquã', site: null, instagram: null },
  { name: 'Camargo', site: null, instagram: null },
  { name: 'Campina das Missões', site: null, instagram: null },
  { name: 'Campinas do Sul', site: null, instagram: null },
  { name: 'Campo Bom', site: null, instagram: null },
  { name: 'Campos Borges', site: null, instagram: null },
  { name: 'Candelária', site: null, instagram: null },
  { name: 'Cândido Godói', site: null, instagram: null },
  { name: 'Canela', site: null, instagram: null },
  {
    name: 'Canoas',
    site: null,
    instagram: 'https://www.instagram.com/prefcanoas/',
  },
  { name: 'Canudos do Vale', site: null, instagram: null },
  { name: 'Capão da Canoa', site: null, instagram: null },
  { name: 'Capela de Santana', site: null, instagram: null },
  { name: 'Capitão', site: null, instagram: null },
  { name: 'Carazinho', site: null, instagram: null },
  { name: 'Carlos Barbosa', site: null, instagram: null },
  { name: 'Carlos Gomes', site: null, instagram: null },
  { name: 'Caseiros', site: null, instagram: null },
  { name: 'Catuípe', site: null, instagram: null },
  {
    name: 'Caxias do Sul',
    site: 'https://caxias.rs.gov.br/',
    instagram: 'https://www.instagram.com/prefacaxiasdosul/',
  },
  { name: 'Centenário', site: null, instagram: null },
  { name: 'Cerro Branco', site: null, instagram: null },
  { name: 'Cerro Grande do Sul', site: null, instagram: null },
  { name: 'Cerro Grande', site: null, instagram: null },
  { name: 'Chapada', site: null, instagram: null },
  { name: 'Charqueadas', site: null, instagram: null },
  { name: 'Chiapetta', site: null, instagram: null },
  { name: 'Ciríaco', site: null, instagram: null },
  { name: 'Colinas', site: null, instagram: null },
  { name: 'Colorado', site: null, instagram: null },
  { name: 'Constantina', site: null, instagram: null },
  { name: 'Coqueiro Baixo', site: null, instagram: null },
  { name: 'Coronel Bicaco', site: null, instagram: null },
  { name: 'Coronel Pilar', site: null, instagram: null },
  { name: 'Cotiporã', site: null, instagram: null },
  { name: 'Crissiumal', site: null, instagram: null },
  { name: 'Cristal do Sul', site: null, instagram: null },
  { name: 'Cristal', site: null, instagram: null },
  { name: 'Cruz Alta', site: null, instagram: null },
  { name: 'Cruzaltense', site: null, instagram: null },
  { name: 'Cruzeiro do Sul', site: null, instagram: null },
  { name: 'Dezesseis de Novembro', site: null, instagram: null },
  { name: 'Dilermando de Aguiar', site: null, instagram: null },
  { name: 'Dois Irmãos das Missões', site: null, instagram: null },
  { name: 'Dois Lajeados', site: null, instagram: null },
  { name: 'Dom Feliciano', site: null, instagram: null },
  { name: 'Dona Francisca', site: null, instagram: null },
  {
    name: 'Eldorado do Sul',
    site: null,
    instagram: 'https://www.instagram.com/prefeldoradodosul/',
  },
  {
    name: 'Encantado',
    site: null,
    instagram: 'https://www.instagram.com/prefeituraencantado',
  },
  { name: 'Encruzilhada do Sul', site: null, instagram: null },
  { name: 'Engenho Velho', site: null, instagram: null },
  { name: 'Entre Rios do Sul', site: null, instagram: null },
  { name: 'Erechim', site: null, instagram: null },
  { name: 'Erval Grande', site: null, instagram: null },
  { name: 'Erval Seco', site: null, instagram: null },
  { name: 'Espumoso', site: null, instagram: null },
  { name: 'Estação', site: null, instagram: null },
  { name: 'Estância Velha', site: null, instagram: null },
  { name: 'Esteio', site: null, instagram: null },
  { name: 'Estrela Velha', site: null, instagram: null },
  {
    name: 'Estrela',
    site: null,
    instagram: 'https://www.instagram.com/governodeestrelars/',
  },
  { name: 'Eugênio de Castro', site: null, instagram: null },
  { name: 'Fagundes Varela', site: null, instagram: null },
  { name: 'Farroupilha', site: null, instagram: null },
  { name: 'Faxinal do Soturno', site: null, instagram: null },
  { name: 'Faxinalzinho', site: null, instagram: null },
  { name: 'Feliz', site: null, instagram: null },
  { name: 'Flores da Cunha', site: null, instagram: null },
  { name: 'Fontoura Xavier', site: null, instagram: null },
  { name: 'Formigueiro', site: null, instagram: null },
  { name: 'Forquetinha', site: null, instagram: null },
  { name: 'Frederico Westphalen', site: null, instagram: null },
  { name: 'Garibaldi', site: null, instagram: null },
  { name: 'General Câmara', site: null, instagram: null },
  { name: 'Gentil', site: null, instagram: null },
  { name: 'Gramado Xavier', site: null, instagram: null },
  { name: 'Gramado', site: null, instagram: null },
  { name: 'Gravataí', site: null, instagram: null },
  {
    name: 'Guaíba',
    site: null,
    instagram: 'https://www.instagram.com/prefeituradeguaiba/',
  },
  { name: 'Guaporé', site: null, instagram: null },
  { name: 'Herveiras', site: null, instagram: null },
  { name: 'Ibarama', site: null, instagram: null },
  { name: 'Ibirapuitã', site: null, instagram: null },
  { name: 'Ibirubá', site: null, instagram: null },
  {
    name: 'Igrejinha',
    site: null,
    instagram: 'https://www.instagram.com/municipio_igrejinha/',
  },
  { name: 'Ilópolis', site: null, instagram: null },
  { name: 'Imigrante', site: null, instagram: null },
  { name: 'Independência', site: null, instagram: null },
  { name: 'Inhacorá', site: null, instagram: null },
  { name: 'Ipê', site: null, instagram: null },
  { name: 'Ipiranga do Sul', site: null, instagram: null },
  { name: 'Iraí', site: null, instagram: null },
  { name: 'Itaara', site: null, instagram: null },
  { name: 'Itapuca', site: null, instagram: null },
  { name: 'Itati', site: null, instagram: null },
  { name: 'Itatiba do Sul', site: null, instagram: null },
  { name: 'Ivorá', site: null, instagram: null },
  { name: 'Jaboticaba', site: null, instagram: null },
  { name: 'Jacuizinho', site: null, instagram: null },
  { name: 'Jaguarão', site: null, instagram: null },
  { name: 'Jaguari', site: null, instagram: null },
  { name: 'Jari', site: null, instagram: null },
  { name: 'Jóia', site: null, instagram: null },
  { name: 'Júlio de Castilhos', site: null, instagram: null },
  { name: 'Lagoa Bonita do Sul', site: null, instagram: null },
  { name: 'Lagoa dos Três Cantos', site: null, instagram: null },
  { name: 'Lagoa Vermelha', site: null, instagram: null },
  { name: 'Lagoão', site: null, instagram: null },
  { name: 'Lajeado do Bugre', site: null, instagram: null },
  { name: 'Lajeado', site: null, instagram: null },
  { name: 'Lavras do Sul', site: null, instagram: null },
  { name: 'Liberato Salzano', site: null, instagram: null },
  { name: 'Mampituba', site: null, instagram: null },
  { name: 'Manoel Viana', site: null, instagram: null },
  { name: 'Maquiné', site: null, instagram: null },
  { name: 'Maratá', site: null, instagram: null },
  { name: 'Marau', site: null, instagram: null },
  { name: 'Marcelino Ramos', site: null, instagram: null },
  { name: 'Mariano Moro', site: null, instagram: null },
  { name: 'Marques de Souza', site: null, instagram: null },
  { name: 'Mata', site: null, instagram: null },
  { name: 'Mato Leitão', site: null, instagram: null },
  { name: 'Maximiliano de Almeida', site: null, instagram: null },
  { name: 'Miraguaí', site: null, instagram: null },
  { name: 'Montauri', site: null, instagram: null },
  { name: 'Monte Alegre dos Campos', site: null, instagram: null },
  { name: 'Montenegro', site: null, instagram: null },
  { name: 'Mormaço', site: null, instagram: null },
  { name: 'Mostardas', site: null, instagram: null },
  { name: 'Muçum', site: null, instagram: null },
  { name: 'Não-me-toque', site: null, instagram: null },
  { name: 'Nonoai', site: null, instagram: null },
  { name: 'Nova Alvorada', site: null, instagram: null },
  { name: 'Nova Bassano', site: null, instagram: null },
  { name: 'Nova Boa Vista', site: null, instagram: null },
  { name: 'Nova Bréscia', site: null, instagram: null },
  { name: 'Nova Esperança do Sul', site: null, instagram: null },
  { name: 'Nova Palma', site: null, instagram: null },
  { name: 'Nova Petrópolis', site: null, instagram: null },
  { name: 'Nova Prata', site: null, instagram: null },
  { name: 'Nova Ramada', site: null, instagram: null },
  { name: 'Nova Roma do Sul', site: null, instagram: null },
  { name: 'Nova Santa Rita', site: null, instagram: null },
  { name: 'Novo Cabrais', site: null, instagram: null },
  { name: 'Novo Hamburgo', site: null, instagram: null },
  { name: 'Novo Tiradentes', site: null, instagram: null },
  { name: 'Novo Xingu', site: null, instagram: null },
  { name: 'Paim Filho', site: null, instagram: null },
  { name: 'Palmeira Das Missões', site: null, instagram: null },
  { name: 'Palmitinho', site: null, instagram: null },
  { name: 'Panambi', site: null, instagram: null },
  { name: 'Pantano Grande', site: null, instagram: null },
  { name: 'Paraíso do Sul', site: null, instagram: null },
  { name: 'Pareci Novo', site: null, instagram: null },
  { name: 'Parobé', site: null, instagram: null },
  { name: 'Passa Sete', site: null, instagram: null },
  { name: 'Passo do Sobrado', site: null, instagram: null },
  { name: 'Passo Fundo', site: null, instagram: null },
  { name: 'Paulo Bento', site: null, instagram: null },
  { name: 'Paverama', site: null, instagram: null },
  { name: 'Pejuçara', site: null, instagram: null },
  { name: 'Pelotas', site: null, instagram: null },
  { name: 'Pinhal Grande', site: null, instagram: null },
  { name: 'Pinhal', site: null, instagram: null },
  { name: 'Pinheiro Machado', site: null, instagram: null },
  {
    name: 'Pinto Bandeira',
    site: 'https://www.pintobandeira.rs.gov.br/',
    instagram: 'https://www.instagram.com/municipiopintobandeira/',
  },
  { name: 'Piratini', site: null, instagram: null },
  { name: 'Planalto', site: null, instagram: null },
  { name: 'Poço das Antas', site: null, instagram: null },
  { name: 'Ponte Preta', site: null, instagram: null },
  { name: 'Portão', site: null, instagram: null },
  {
    name: 'Porto Alegre',
    site: 'https://prefeitura.poa.br/',
    instagram: 'https://www.instagram.com/prefpoa/',
  },
  { name: 'Porto Lucena', site: null, instagram: null },
  { name: 'Porto Mauá', site: null, instagram: null },
  { name: 'Porto Xavier', site: null, instagram: null },
  { name: 'Pouso Novo', site: null, instagram: null },
  { name: 'Presidente Lucena', site: null, instagram: null },
  { name: 'Progresso', site: null, instagram: null },
  { name: 'Protásio Alves', site: null, instagram: null },
  { name: 'Putinga', site: null, instagram: null },
  { name: 'Quaraí', site: null, instagram: null },
  { name: 'Quevedos', site: null, instagram: null },
  { name: 'Quinze de Novembro', site: null, instagram: null },
  { name: 'Redentora', site: null, instagram: null },
  { name: 'Relvado', site: null, instagram: null },
  { name: 'Restinga Seca', site: null, instagram: null },
  { name: 'Rio Pardo', site: null, instagram: null },
  {
    name: 'Roca Sales',
    site: null,
    instagram: 'https://www.instagram.com/prefeitura_rocasales/',
  },
  { name: 'Rodeio Bonito', site: null, instagram: null },
  { name: 'Rolante', site: null, instagram: null },
  { name: 'Ronda Alta', site: null, instagram: null },
  { name: 'Rondinha', site: null, instagram: null },
  { name: 'Rosário do Sul', site: null, instagram: null },
  { name: 'Sagrada Família', site: null, instagram: null },
  { name: 'Salto do Jacuí', site: null, instagram: null },
  { name: 'Salvador do Sul', site: null, instagram: null },
  { name: 'Santa Clara do Sul', site: null, instagram: null },
  { name: 'Santa Cruz do Sul', site: null, instagram: null },
  { name: 'Santa Margarida do Sul', site: null, instagram: null },
  { name: 'Santa Maria do Herval', site: null, instagram: null },
  {
    name: 'Santa Maria',
    site: null,
    instagram: 'https://www.instagram.com/prefeituradesantamaria',
  },
  { name: 'Santa Rosa', site: null, instagram: null },
  { name: 'Santa Tereza', site: null, instagram: null },
  { name: 'Santana da Boa Vista', site: null, instagram: null },
  { name: 'Santiago', site: null, instagram: null },
  { name: 'Santo Ângelo', site: null, instagram: null },
  { name: 'Santo Antônio da Patrulha', site: null, instagram: null },
  { name: 'Santo Augusto', site: null, instagram: null },
  { name: 'Santo Cristo', site: null, instagram: null },
  { name: 'São Borja', site: null, instagram: null },
  { name: 'São Domingos do Sul', site: null, instagram: null },
  { name: 'São Francisco de Assis', site: null, instagram: null },
  { name: 'São Francisco de Paula', site: null, instagram: null },
  { name: 'São Gabriel', site: null, instagram: null },
  { name: 'São Jerônimo', site: null, instagram: null },
  { name: 'São João da Urtiga', site: null, instagram: null },
  { name: 'São João do Polêsine', site: null, instagram: null },
  { name: 'São Jorge', site: null, instagram: null },
  { name: 'São José Das Missões', site: null, instagram: null },
  { name: 'São José do Herval', site: null, instagram: null },
  { name: 'São José do Inhacorá', site: null, instagram: null },
  { name: 'São José do Norte', site: null, instagram: null },
  { name: 'São José do Sul', site: null, instagram: null },
  {
    name: 'São Leopoldo',
    site: null,
    instagram: 'https://www.instagram.com/prefasaoleo/',
  },
  { name: 'São Marcos', site: null, instagram: null },
  { name: 'São Martinho da Serra', site: null, instagram: null },
  { name: 'São Miguel das Missões', site: null, instagram: null },
  { name: 'São Paulo das Missões', site: null, instagram: null },
  { name: 'São Pedro da Serra', site: null, instagram: null },
  { name: 'São Pedro das Missões', site: null, instagram: null },
  { name: 'São Pedro do Butiá', site: null, instagram: null },
  { name: 'São Pedro do Sul', site: null, instagram: null },
  {
    name: 'São Sebastião do Caí',
    site: null,
    instagram: 'https://www.instagram.com/prefeiturasscai/',
  },
  { name: 'São Sepé', site: null, instagram: null },
  { name: 'São Valentim', site: null, instagram: null },
  { name: 'São Vendelino', site: null, instagram: null },
  { name: 'Sapiranga', site: null, instagram: null },
  { name: 'Sapucaia do Sul', site: null, instagram: null },
  { name: 'Sarandi', site: null, instagram: null },
  { name: 'Seberi', site: null, instagram: null },
  { name: 'Sede Nova', site: null, instagram: null },
  { name: 'Segredo', site: null, instagram: null },
  { name: 'Senador Salgado Filho', site: null, instagram: null },
  { name: 'Sentinela do Sul', site: null, instagram: null },
  { name: 'Serafina Corrêa', site: null, instagram: null },
  { name: 'Sério', site: null, instagram: null },
  { name: 'Sertão', site: null, instagram: null },
  { name: 'Severiano de Almeida', site: null, instagram: null },
  { name: 'Silveira Martins', site: null, instagram: null },
  {
    name: 'Sinimbu',
    site: null,
    instagram: 'https://www.instagram.com/prefasinimbu/',
  },
  { name: 'Sobradinho', site: null, instagram: null },
  { name: 'Soledade', site: null, instagram: null },
  { name: 'Tabaí', site: null, instagram: null },
  { name: 'Tapes', site: null, instagram: null },
  {
    name: 'Taquara',
    site: null,
    instagram: 'https://www.instagram.com/preftaquara/',
  },
  { name: 'Taquari', site: null, instagram: null },
  { name: 'Taquaruçu do Sul', site: null, instagram: null },
  { name: 'Tenente Portela', site: null, instagram: null },
  {
    name: 'Teutônia',
    site: null,
    instagram: 'https://www.instagram.com/prefeiturateutonia/',
  },
  { name: 'Tio Hugo', site: null, instagram: null },
  { name: 'Tiradentes do Sul', site: null, instagram: null },
  { name: 'Toropi', site: null, instagram: null },
  { name: 'Torres', site: null, instagram: null },
  { name: 'Travesseiro', site: null, instagram: null },
  { name: 'Três Arroios', site: null, instagram: null },
  {
    name: 'Três Coroas',
    site: null,
    instagram: 'https://www.instagram.com/prefeitura_trescoroas/',
  },
  { name: 'Três Forquilhas', site: null, instagram: null },
  { name: 'Três Palmeiras', site: null, instagram: null },
  { name: 'Três Passos', site: null, instagram: null },
  { name: 'Trindade do Sul', site: null, instagram: null },
  { name: 'Tucunduva', site: null, instagram: null },
  { name: 'Tunas', site: null, instagram: null },
  { name: 'Tupanci do Sul', site: null, instagram: null },
  { name: 'Tupanciretã', site: null, instagram: null },
  { name: 'Tupandi', site: null, instagram: null },
  { name: 'Ubiretama', site: null, instagram: null },
  { name: 'União da Serra', site: null, instagram: null },
  { name: 'Uruguaiana', site: null, instagram: null },
  { name: 'Vale do Sol', site: null, instagram: null },
  { name: 'Vale Real', site: null, instagram: null },
  { name: 'Vale Verde', site: null, instagram: null },
  { name: 'Vanini', site: null, instagram: null },
  { name: 'Venâncio Aires', site: null, instagram: null },
  { name: 'Vera Cruz', site: null, instagram: null },
  { name: 'Veranópolis', site: null, instagram: null },
  { name: 'Vespasiano Correa', site: null, instagram: null },
  { name: 'Viadutos', site: null, instagram: null },
  { name: 'Viamão', site: null, instagram: null },
  { name: 'Vicente Dutra', site: null, instagram: null },
  { name: 'Vila Flores', site: null, instagram: null },
  { name: 'Vila Maria', site: null, instagram: null },
  { name: 'Vista Alegre do Prata', site: null, instagram: null },
  { name: 'Vista Alegre', site: null, instagram: null },
  { name: 'Xangri-lá', site: null, instagram: null },
];

export function GET(): Response {
  return Response.json({
    meta: {
      source: 'https://www.diariooficial.rs.gov.br/materia?id=998883',
    },
    data: municipios,
  });
}
